version: '2.1'
services:

### Application Code Container

  tuto_application:
      container_name: tuto_app
#you can comment out the next line
      restart: always
      build: ./server
      image: tuto/tuto_app
      ports:
        # change the local-port
        # [local-ip]:[local-port]:[container-port]
        - "127.0.0.1:8080:8080"
